### PR TITLE
Refactor to add support for chuga’s fork of node-slack

### PR DESCRIPTION
**Pull request by joakim**
- Swapped out node-slack for chuga's fork which uses Slack's new WebHook API
- Switched to `setInterval` instead of node-cron
- Refactored the code and moved the bulk of it into slackus.js
- Improved configuration options
- Added a JSHint file

I also took the liberty to add my name to the license, but that's not a requirement for this PR, feel free to take it out :)

See also #1

### CODE REVIEW

**Comment by jonathanwiesel** [comment]
Looks great :+1: 

However I noticed that "mentions" functionality was removed, if you could add it back that would be nice. I think is very helpful when having forum managers.

Also, if you could pull the last upstream changes (heroku button related) and make the pertinent modifications to the `app.json` file to use the same environment variables that would be great.

Other than that seems like a good go to me.

**Comment by joakim** [comment]
:+1: 

I don't remember why I removed the mentions functionality, maybe I just forgot about it. Anyway, I'll add it back in. I also noticed your upstream changes, I'll merge those in as well… when I have time later today or tomorrow :)

**Comment by joakim** [comment]
It took me 20 days..! But now there's support for mentions, some useful links in the readme, and the Heroku deploy button has been added back.

**Comment by jonathanwiesel** [comment]
Looks great @joakim, thanks a lot for sharing :+1:.

**Pull request merged**
